# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details and example of testing OPTIONAL modules

language: php

dist: trusty

php:
  - 5.4

env:
  matrix:
    - DB=MYSQL CORE_RELEASE=3.6

matrix:
  include:
    - php: 5.4
      env:
        - DB=PGSQL
        - CORE_RELEASE=3.6
    - php: 5.5
      env:
        - DB=MYSQL
        - CORE_RELEASE=3.6
    - php: 5.6
      env:
        - DB=MYSQL
        - PHPCS_TEST=1
        - CORE_RELEASE=3
    - php: 7.1
      env:
        - DB=MYSQL
        - CORE_RELEASE=3.6

before_script:
  - composer self-update || true
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs design-bridge/src/ design-bridge/tests/ -n; fi
  - vendor/bin/phpunit design-bridge/tests/
